POST http://localhost:6500/posts
Content-Type: application/json
{
 "title": "Title type and javascript",
 "postType": "post",
 "slug": "new-with-nestjs-t6",
 "status": "draft",
 "content": "test content",
 "schema": "{\r\n    \"@context\": \"https:\/\/schema.org\",\r\n    \"@type\": \"Person\"\r\n  }",
 "featuredImageUrl": "http://localhost.com/images/image1.jpg",
 "publishedOn": "2024-03-16T07:46:32+0000",
 "metaOptions": 
    {
      "metaValue": "{\"sidebarEnabled\": true, \"footerActive\": true}"
    },
  "authorId": 1,
  "tags":[1, 2]
}

