POST http://localhost:6500/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJlbWFpbCI6ImpvaG4xQGRvZS5jb20iLCJpYXQiOjE3NDQzNjMzNjMsImV4cCI6MTc0NDM2Njk2MywiYXVkIjoibG9jYWxob3N0OjY1MDAiLCJpc3MiOiJsb2NhbGhvc3Q6NjUwMCJ9.WQLHNMAk9bk4Dikm7FtR0xkuMB2RW-_rjlb5aP-IaUw
{
  "users": [
    {
      "firstName": "Mark",
      "lastName": "Doe",
      "email": "mark@doe22.com",
      "password": "Password123#"
    },
    {
      "firstName": "Tom",
      "lastName": "Doe",
      "email": "tom@doe22.com",
      "password": "Password123#"
    }
  ]
}


