POST http://localhost:6500/auth/refresh-tokens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJlbWFpbCI6ImpvaG4xQGRvZS5jb20iLCJpYXQiOjE3NDQ2MzI0MzgsImV4cCI6MTc0NDYzNjAzOCwiYXVkIjoibG9jYWxob3N0OjY1MDAiLCJpc3MiOiJsb2NhbGhvc3Q6NjUwMCJ9.9qekpTU06z8YX4t0HUZYjVp4Qq7Azx4fGrBLgnd5XUs
{
 "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJpYXQiOjE3NDQ2MzI0MzgsImV4cCI6MTc0NDYzNjAzOCwiYXVkIjoibG9jYWxob3N0OjY1MDAiLCJpc3MiOiJsb2NhbGhvc3Q6NjUwMCJ9.vrZIztx2iSJy4Fef-1p6TKhcnzZWeypsA95OW_ooxGE"
}
